Make output path of provenance.log configurable
cta-observatory/ctapipe pull request #1432
Opened 2020-09-29 09:23 UTC by Bultako

This PR intends to solve issue #1421 
It adds `provenance_dir` as a configurable trait of a Tool.

2020-09-29 11:59 UTC, kosack submitted a review, later dismissed

2020-09-29 12:35 UTC, MaxNoe requested changes
At the moment, this is a single file.

So why add an output directory with a hard-coded filename and not an option for the filename itself?

Please change to a `provenance_log =Path(...)` trait for the output filename

2020-09-29 12:37 UTC, kosack commented
good point - perhaps by default set the filename to the name of the tool (tools should have a .name attribute), so you get something like "./ctapipe-something-tool.prov.log", and then let the user specify any path/name.

2020-09-29 13:43 UTC, Bultako commented
I've added `prov_filename` attribute as described by @kosack, so to have independent `prov_dir` and  `prov_filename` attributes for Tools with default values `cwd` and `tool.name.prov.log`

2020-09-29 13:50 UTC, MaxNoe commented
I think you misunderstood what we had in mind. 

The directory trait is unnecessary, since an argument for the file can be a relative or absolute path to any directory.
So this trait should be removed.

Then a trait `provenance_log` with type `ctapipe.core.traits.Path` should be added.
@kosack proposed that this trait should have a default value containing the name of the tool.

I think this can be achieved using a default method like this:

```
from traitlets import default
from ctapipe.core.traits import Path

class Tool():
    ...
    provenance_log = Path()
    
    @default('provenance_log')
    def _default_provenance_log(self):
        return self.name + '.provenance.log'
     
```

2020-09-29 14:41 UTC, MaxNoe approved these changes
LGTM, thank you!

2020-09-29 14:43 UTC, Bultako commented
Thanks @MaxNoe 
Indeed, I had completely misunderstood the point, I've made the suggested changes, having a single `provenance_log` attribute of type `Path()`

It now comes to my mind the use case when `provenance_log` value is set to a non-existing directory path, do we raise an error or create that path? in the latter case, should we implement a method in the `Path()` trait to create that non-existing folder? or we do use the [Pathlib.Path.mkdir()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) method instead?

2020-09-29 14:43 UTC, MaxNoe commented
Creating the directory could be nice, yes.

2020-09-29 15:39 UTC, MaxNoe approved these changes

2020-10-01 13:48 UTC, kosack approved these changes

2020-10-01 14:09 UTC, MaxNoe commented
Somehow the status update from travis was not received, I restarted the build

2020-10-02 10:07 UTC, merged