Change definition of concentration_cog, fixes #1571
cta-observatory/ctapipe pull request #1572
Opened 2021-01-11 17:10 UTC by maxnoe

This changes the definition of concentration_cog from
"the three closest pixels to the cog" to
"pixel closer to the cog than the pixel diameter".

This has two advantages:
* no need for argsort: 50 % faster
* works if a masked geometry / image is passed as expected, before
  the three closest pixels to the cog could be very far away from the
  cog, e.g. for muon rings.

2021-01-11 17:29 UTC, kosack requested changes
Need to update the help string in `ctapipe.containers.ConcentrationContainer` as well, since it still says "Percentage of photo-electrons in the three pixels closest to the cog"

2021-01-12 13:04 UTC, maxnoe commented
@kosack done

2021-01-12 13:44 UTC, kosack approved these changes

2021-04-15 08:35 UTC, HealthyPear approved these changes

2021-04-15 10:14 UTC, merged