Faster muon reconstruction using numba
cta-observatory/ctapipe pull request #1583
Opened 2021-01-28 15:26 UTC by RuneDominik

Small changes to utilize numba for faster muon reconstruction. The major part in the ~1/3 decreased time required for processing muon events is gained in the direct implementation of a gaussian cdf, where the math modules erf-function is needed since standard numba is not aware of scipy. Further speedup is gained from decorating the chord_length function. This does, however, require the definition of an input and output layout that restricts the usage of the function to inputs of dimension 1 (which should be the use-case). As a result, the corresponding unit-tests are failing, as these test the function with scalar values.

2021-01-28 15:47 UTC, maxnoe requested changes

2021-01-28 15:47 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +# Define numba vectorized gaussian cdf
Remove this and add a proper docstring to the function.

See: https://numpydoc.readthedocs.io/en/latest/format.html

2021-01-28 15:47 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +    return 0.5*(1 + erf((x-mu)/(np.sqrt(2*sig**2))))
Please use the black formatting pre-commit hook, see https://cta-observatory.github.io/ctapipe/getting_started/index.html

2021-01-28 15:47 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +    # Define Gaussian cdf for numba usage
This comment does not really give more information since the function is aptly called `gaussian_cdf`

2021-01-29 14:43 UTC, RuneDominik commented
Included @maxnoe requests and swapped guvectorization to normal vectorization, as it includes scalar inputs without performance loss.

2021-01-29 16:14 UTC, kosack commented
The pipelines are failing for another reason, see #1585   They should work once that is merged.

2021-02-02 11:39 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +        gaussian standart deviation
typo standard.

2021-02-02 11:39 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +        gaussian standart deviation
Also with `vectorize` all values can also be `ndarrays`

2021-02-02 11:41 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +    return 0.5 * (1 + erf((x - mu) / (np.sqrt(2 * sig ** 2))))
sqrt is a pretty slow operation. sig is positive. So maybe we can gain something by defining a constant `sqrt2` and removing the sqrt here?

2021-02-02 19:01 UTC, maxnoe approved these changes

2021-02-03 10:57 UTC, kosack approved these changes

2021-02-03 10:57 UTC, merged