Fix dl1 merge tool not writing correct metadata
cta-observatory/ctapipe pull request #1614
Opened 2021-02-18 14:45 UTC by maxnoe

The subarray pointing table was missing metadata and the merge tool
always set the product version to 1.0, also when merging newer files.

* Check and use CTA PRODUCT DATA MODEL VERSION when merging
* Remove fix for merging ctapipe 0.8 files that lead to the missing
metadata
* Actually run stage1 on the merged file result

This shoudl fix the dl1 merging.

I am not really happy with the tests yet for merging, we at least two runs from the same production to test properly.

2021-02-18 15:33 UTC, LukasNickel requested changes

2021-02-18 15:33 UTC, LukasNickel commented on ctapipe/utils/index_finder.py
> +        values = np.unique(values)
This line is not needed / breaks the test.

2021-02-18 15:33 UTC, LukasNickel commented on ctapipe/utils/index_finder.py
> +    Duplicated keys will be ignored.
Values rather than keys?

Also I would add an warning here to avoid hard to find bugs if someone uses this class for other reasons

2021-02-19 15:31 UTC, maxnoe commented
@kosack @LukasNickel @Hckjs I think this is ready now, please review.

2021-02-19 16:16 UTC, Hckjs commented
Don't need that anymore then, do we?

https://github.com/cta-observatory/ctapipe/blob/fb9324a762e73fae715982f7d52b364b508ce3a2/ctapipe/tools/dl1_merge.py#L347-L355

2021-02-19 16:24 UTC, maxnoe commented
Ah right, yes.

2021-02-19 17:29 UTC, LukasNickel approved these changes

2021-02-19 17:38 UTC, Hckjs approved these changes

2021-02-19 17:50 UTC, merged