Show installed io plugins in ctapipe info, fixes #1540
cta-observatory/ctapipe pull request #1630
Opened 2021-02-19 16:48 UTC by maxnoe

2021-02-19 17:17 UTC, kosack submitted a review, later dismissed

2021-02-23 15:40 UTC, nbiederbeck commented on ctapipe/tools/info.py
> +        print(f"{name:>20s} -- {version}")
Can we print a "no io plugins installed" if that is the case?

2021-02-24 10:43 UTC, HealthyPear requested changes
I also think we should be explicit if no I/O plugins are installed.

2021-02-24 12:44 UTC, maxnoe commented
@HealthyPear @nbiederbeck done

2021-02-24 12:47 UTC, HealthyPear commented
> @HealthyPear @nbiederbeck done

Sure you have pushed new modifications?
I don't see new commits

2021-02-24 12:48 UTC, maxnoe commented
Sorry, the black commit hook complained and I didn't realized I hadn't commited.

2021-02-24 12:48 UTC, nbiederbeck approved these changes

2021-02-24 12:49 UTC, HealthyPear approved these changes

2021-02-24 15:15 UTC, merged