Add flags to enforce recomputation of dl1/dl2
cta-observatory/ctapipe pull request #1776
Opened 2021-08-05 13:26 UTC by LukasNickel

#1726 removed the possibility to rerun stage1/process with the goal of recomputing the DL1 information on a file with both DL1a and DL1b.
This can be useful to test different cleanings or add noise to the images (#1723).

Could be done without the `if` clauses adding another `or`  aswell. I just felt like its the easiest to understand (especially if the compute logic changes at some point.)

2021-08-05 13:38 UTC, HealthyPear commented
I think we should specify **DL1b** here, since the input file is one that comes from `ctapipe-process` and not the `simtel` file - unless I misunderstood the context

2021-08-05 13:40 UTC, LukasNickel commented
> I think we should specify **DL1b** here, since the input file is one that comes from `ctapipe-process` and not the `simtel` file - unless I misunderstood the context

You mean recomputing DL1b?
I would like to recompute DL1a as well and the code makes no difference: Both are done in the same call to the `ImageProcessor`

2021-08-05 13:41 UTC, kosack requested changes
other than a small naming change, this looks fine.

2021-08-05 13:41 UTC, kosack commented on ctapipe/tools/process.py
> +            "recompute_dl1",
I suggest calling this  alias `--recompute-dl1` (using a dash not an underscore) as we do with other command-line arguments.  Same for `--recompute-dl2`

2021-08-05 13:42 UTC, maxnoe commented
> I would like to recompute DL1a as well and the code makes no difference: Both are done in the same call to the ImageProcessor

How can you *re*compute DL1a? If it is a simtel file, you always need to calculate it. If it is a DL1 file, you cannot recompute it, since the DL0 is not there.

2021-08-05 13:44 UTC, LukasNickel commented
> > I would like to recompute DL1a as well and the code makes no difference: Both are done in the same call to the ImageProcessor
> 
> How can you _re_compute DL1a? If it is a simtel file, you always need to calculate it. If it is a DL1 file, you cannot recompute it, since the DL0 is not there.

You can compute a new cleaning mask from existing dl1 or not?
Are we talking about semantics or am I missing something fundamental here?

2021-08-05 13:47 UTC, maxnoe commented
> You can compute a new cleaning mask from existing dl1 or not?

Redoing the cleaning is not what I think of "recomputing dl1a". 
If this is about redoing the cleaning, then yes, that should be possible. Maybe an explicit "redo_cleaning"?

2021-08-05 13:48 UTC, LukasNickel commented
> > You can compute a new cleaning mask from existing dl1 or not?
> 
> Redoing the cleaning is not what I think of "recomputing dl1a".
> If this is about redoing the cleaning, then yes, that should be possible. Maybe an explicit "redo_cleaning"?

It is also about modifying the images though (adding noise / psf smearing / ...)

2021-08-05 16:20 UTC, kosack submitted a review, later dismissed

2021-08-12 13:43 UTC, nbiederbeck requested changes

2021-08-13 08:23 UTC, nbiederbeck approved these changes

2021-08-23 14:22 UTC, kosack approved these changes

2021-08-23 14:22 UTC, merged