options to write R0 and R1 waveforms
cta-observatory/ctapipe pull request #1799
Opened 2021-10-12 13:53 UTC by kosack

For debugging and benchmarking purposes, this adds two options to `DataWriter`: 
* `write_raw_waveforms`: writes the `R0CameraContainer` (waveforms for all channels) to  `/r0/telescope/tel_XXX`
* `write_waveforms`: writes the `R1CameraContainer` (pre-calibrated, gain-selected waveforms) to  `/r1/telescope/tel_XXX`

also add option to transform waveform for more efficient storage

This allows for event-wise benchmarks or cross-checks of data at  all data levels (DL0 currently not supported, as in the current implementation, DL0 and R1 are the same and we have not yet decided how to store sparse waveforms)

![image](https://user-images.githubusercontent.com/11677812/136969067-e7f65fea-d432-4b3b-a444-24d166a8c800.png)

2021-11-16 12:15 UTC, maxnoe commented
@kosack do you mind if I rebase this branch and fix the pyflakes issue?

2021-11-16 13:03 UTC, kosack commented
sure no problem.

2021-11-16 13:32 UTC, maxnoe commented
Looks like matplotlib 3.5 dropped

2021-11-16 16:18 UTC, kosack commented on ctapipe/io/datawriter.py
> +        help="Store R1 waveforms if available", default_fill_value=False
hmm. that may be a completion typo.  It should be default_value.   I'm surprised it didnt' raise an error, though I have not yet written explicit tests.

2021-11-16 16:22 UTC, kosack commented on ctapipe/io/datawriter.py
> +        help="Store R1 waveforms if available", default_fill_value=False
Ah, I see, unknown keywords fail with a warning currently: 
```
DeprecationWarning: metadata {'default_fill_value': 0} was set from the constructor. With traitlets 4.1, metadata should be set using the .tag() method, e.g., Int().tag(key1='value1', key2='value2')
```
So it was not obvious that it was a typo

2021-11-16 17:54 UTC, maxnoe requested changes
Shouldn't we just call them `write_r0_waveforms`, `write_r1_waveforms` and `write_dl0_waveforms`? (Adding an option for dl0?)

2021-11-16 17:55 UTC, maxnoe commented on ctapipe/io/datawriter.py
> +    waveform_dtype = Unicode(default_value="int32").tag(config=True)
prefix with `r1` since it only applies to r1?

2021-11-17 14:07 UTC, kosack commented
> Shouldn't we just call them write_r0_waveforms, write_r1_waveforms and write_dl0_waveforms? (Adding an option for dl0?)

It was just to avoid jargon since we don't use the data level in the other options either (write_parameters vs write_dl1_parameters), but in the end it may be clearer - I don't mind either way

2022-01-13 13:09 UTC, maxnoe approved these changes

2022-01-28 09:14 UTC, HealthyPear approved these changes

2022-01-28 09:17 UTC, maxnoe commented
> It was just to avoid jargon since we don't use the data level in the other options either 

Let me come back to this. I think we really should put the explicit data levels here. These are well defined within the cta data model. Where I did not immediately get to what `waveforms` or `raw_waveforms` refer. Is it `DL0` and `R1`? or `R1` and `R0`?

2022-01-28 09:18 UTC, maxnoe commented
But the info is in the help string. So fine, let's merge.

2022-01-28 09:18 UTC, merged