Fix multiplicity check in ShowerProcessor and make it configurable
cta-observatory/ctapipe pull request #1875
Opened 2022-04-12 08:50 UTC by maxnoe

The code was requiring at least three! telescopes, while also the debug log output implied 2 and we should not hard code a minimum of 3 telescopes for stereo reconstruction.

2022-04-12 08:50 UTC, LukasNickel submitted a review, later dismissed

2022-04-12 08:51 UTC, nbiederbeck submitted a review, later dismissed

2022-04-12 09:28 UTC, kosack requested changes
This wasn't really meant to be a multiplicity cut for performance, but to just prevent events with less than 2 telescopes being processed (since the algorithm requires at least 2).    

Cuts on multiplicity should come later when doing the optimization or quality classification.   At the DL2 level, we should get all events, even ones with only 2 telescopes.    Later when making an IRF, you have the option to choose a tighter cut, however,

Remember we need to support event quality-types, so you could imagine putting all multiplicity-2 events in their own class. You don't want to drop them before that,

2022-04-12 09:47 UTC, LukasNickel commented
The reason for changing this in the first place was that it applied a cut at 3 not 2 telescopes, despite the comments suggesting otherwise.
(> vs >=)

Event classes is a valid consideration though

2022-04-12 10:02 UTC, maxnoe commented
@kosack I am not clear what you want us to change? You think the option should be removed and we should have a hard coded `>= 2`?

2022-04-12 11:20 UTC, kosack commented
> @kosack I am not clear what you want us to change? You think the option should be removed and we should have a hard coded >= 2?

Yes, however I suppose we can leave it as an option, but the idea was not that this is a minimal cut so that the algorithm works, not the final cut for performance reasons.  Maybe just adding something to the help string would be enough?  I just want to avoid people thinking this is where they should apply the multiplicity cut, which in reality may be more complex and is applied in the DL2→DL3 step.

Fixing it to not require 3 is obviously  a good thing however!

2022-04-12 11:21 UTC, kosack approved these changes

2022-04-12 11:28 UTC, maxnoe commented
> Yes, however I suppose we can leave it as an option, but the idea was *not* that this is a minimal cut so that the algorithm works, not the final cut for performance reasons. 

First not (emphasis mine) not intended?

2022-04-12 11:28 UTC, maxnoe commented
I am fine with just checking `>= 2` and not making it configurable. Everything else can be done after.

2022-04-12 14:26 UTC, maxnoe commented
After realizing the issue described here #1876, I went ahead and added the fix here.

With this, the `ShowerProcessor` is now able to be configured to use both `HillasIntersection` and `HillasReconstructor`, we do really check for `N < 2`, not `N > 2`, and the quality query is properly taken into account.

2022-04-12 14:30 UTC, maxnoe commented
This is a breaking change now, since it changes the API of the reconstructors and the corresponding config files need to be adapted, anyways, let's make a quick new release and everybody should just skip 0.13

2022-04-12 14:42 UTC, nbiederbeck requested changes

2022-04-12 14:48 UTC, maxnoe commented on ctapipe/reco/hillas_reconstructor.py
>      def _predict(
Only that in the refactoring done before, `__call__` was introduced only for `HillasReconstructor`, not for `HillasIntersection` and `predict` was made `_predict` here.

2022-04-12 14:51 UTC, maxnoe commented on ctapipe/reco/hillas_intersection.py
> +            if all(self.check_parameters(dl1.parameters))
actually, `all` is faster for few elements

2022-04-12 14:55 UTC, maxnoe commented on ctapipe/tools/tests/resources/stage2_config.json
> +                    ["enough pixels", "lambda p: p.morphology.num_pixels > 3"]
The check was `leakage < 2`, which is always true. I made all files consistent. We can talk about introducing a leakage cut by default, but I wouldn't do it here

2022-04-12 14:57 UTC, nbiederbeck commented on ctapipe/tools/tests/resources/stage2_config.json
> +                    ["enough pixels", "lambda p: p.morphology.num_pixels > 3"]
+1 for consistency
and sorry I didn't check the content of that line

2022-04-12 14:59 UTC, nbiederbeck commented on ctapipe/reco/hillas_reconstructor.py
>      def _predict(
Got it, thanks

2022-04-12 15:36 UTC, maxnoe commented on ctapipe/reco/hillas_reconstructor.py
> +        if any([h.width.value == 0 for h in hillas_dict.values()]):
moved to `Reconstructor`

2022-04-12 16:35 UTC, maxnoe commented
I think this is ready now and a big improvement. The code in both reconstructors could be a lot better though I think, but I'd keep that for another PR.

2022-04-12 17:05 UTC, kosack approved these changes
seems to work fine

2022-04-13 07:08 UTC, nbiederbeck approved these changes

2022-04-13 10:01 UTC, kosack commented on ctapipe/reco/tests/test_hillas_intersection.py
> +        alt=90 * u.deg - zen_pointing, az=0 * u.deg, frame=altaz
You can also just write 'altaz' as a string I think.

2022-04-13 12:15 UTC, maxnoe commented
I had to update the notebook, please review again. It's now also much more up-to-date which what is currently there in ctapipe (Using ImageProcessor, ShowerProcessor and DataWriter)

2022-04-13 12:54 UTC, maxnoe commented
I processed 10 La Palma gamma-diffuse Prod5b runs, works very nicely. Comparison of current master vs. this branch:

![multiplicity_shower_processor](https://user-images.githubusercontent.com/5488440/163184539-b72306a5-8687-4ebb-a35c-2802861caf30.png)

![theta2_shower_processor](https://user-images.githubusercontent.com/5488440/163184548-ff61321f-8cd7-48c7-9dd0-95b98636a376.png)

2022-04-13 12:58 UTC, kosack commented
Do you understand why there is a difference for multiplicity 3+ events? Shouldn't it be identical?

2022-04-13 13:12 UTC, maxnoe commented on ctapipe/reco/hillas_reconstructor.py
> +        if any([h.width.value == 0 for h in hillas_dict.values()]):
@kosack width is divided by in the weighting, which is why the check is for exactly 0

2022-04-13 13:16 UTC, maxnoe commented
> Do you understand why there is a difference for multiplicity 3+ events? Shouldn't it be identical?

I am checking now, I think I did not adapt the config correctly I used.

2022-04-13 13:43 UTC, maxnoe commented
I indeed forgot to change `ShowerQualityQuery` to `StereoQualityQuery` in my config file. With that fixed, it matches my expectation:

![Uploading theta2_shower_processor.png…]()

2022-04-13 13:44 UTC, nbiederbeck approved these changes

2022-04-13 14:15 UTC, merged