Read dl2 in hdf5eventsource
cta-observatory/ctapipe pull request #1940
Opened 2022-06-20 14:29 UTC by maxnoe

2022-06-20 14:30 UTC, kosack commented
Might want to wait for #1899 before merging this (impact parameters in DL2).

2022-06-26 18:08 UTC, maxnoe commented
@kosack Done and rebased

2022-06-27 08:40 UTC, nbiederbeck approved these changes

2022-06-28 13:02 UTC, nbiederbeck commented on ctapipe/io/hdf5eventsource.py
> +                    self.log.warning("Unknown DL2 stereo group %s", kind)
unknown telescope group

2022-06-28 13:08 UTC, nbiederbeck approved these changes

2022-06-29 06:59 UTC, nbiederbeck commented on ctapipe/io/hdf5eventsource.py
> +                        print(kind, algorithm, tel_id, key)
remove this line

2022-06-29 06:59 UTC, nbiederbeck requested changes

2022-06-29 06:59 UTC, nbiederbeck commented on ctapipe/io/hdf5eventsource.py
> +                        print(kind, algorithm, tel_id, key)
remove this print function

2022-06-29 12:05 UTC, maxnoe commented
@nbiederbeck Fixed. This will (if not directly, then at least semantically) conflict with #1949.

I would propose to merge this PR first to get the basic functionality in and then I can rebase the other one.

2022-06-29 12:10 UTC, nbiederbeck approved these changes

2022-06-29 12:18 UTC, LukasNickel approved these changes

2022-06-29 12:41 UTC, merged