Add pixel, channel, sample information to CameraReadout, update OpticsDescription
cta-observatory/ctapipe pull request #2019
Opened 2022-07-15 11:03 UTC by maxnoe

This adapts our instrument data model a bit to get more in line with what we already know from the DL0 data model and it makes the optics tables in the file more consistent.

The `tel_type` attribute is moved from the `TelescopeDescription` to the `OpticsDescription` as `size_type` to avoid overriding the builin `type`.

A new enum `ReflectorShape` is introduced for OpticsDescription and it is deduced from simtel metadata  files where it is available and was added to the known telescopes in the guessing table.

The optics table now only contains one row per optics description, not one per telescope type:

On this branch:
```
optics_name size_type reflector_shape mirror_area num_mirrors num_mirror_tiles equivalent_focal_length effective_focal_length
ASTRI SST SCHWARZSCHILD_COUDER 14.126235008239746 2 2 2.1500000953674316 2.1519100666046143
MST MST HYBRID 106.2413558959961 1 86 16.0 16.445049285888672
LST LST PARABOLIC 386.7332458496094 1 198 28.0 29.30565071105957
```

On master:

```
description name type mirror_area num_mirrors num_mirror_tiles equivalent_focal_length effective_focal_length
MST_MST_NectarCam MST MST 106.2413558959961 1 86 16.0 16.445049285888672
LST_LST_LSTCam LST LST 386.7332458496094 1 198 28.0 29.30565071105957
MST_MST_FlashCam MST MST 106.2413558959961 1 86 16.0 16.445049285888672
SST_ASTRI_CHEC ASTRI SST 14.126235008239746 2 2 2.1500000953674316 2.1519100666046143
```

We also drop support for older data model version.

2022-07-18 09:11 UTC, nbiederbeck approved these changes

2022-07-18 16:07 UTC, kosack submitted a review, later dismissed

2022-07-22 08:15 UTC, nbiederbeck requested changes

2022-07-22 08:15 UTC, nbiederbeck commented on ctapipe/io/datawriter.py
> +            is not included in SubarrayDescription
typo: now

2022-07-22 08:23 UTC, maxnoe commented on ctapipe/io/datawriter.py
> +            is not included in SubarrayDescription
fixed

2022-07-22 08:25 UTC, nbiederbeck submitted a review, later dismissed

2022-07-22 11:19 UTC, maxnoe commented
@kosack This is ready for review now. I think it is a big improvement.

2022-07-22 16:17 UTC, kosack requested changes
The repr of `TelescopeDescription` fails since self.type is still in there:

```py3
>>> source.subarray.tel[1]
AttributeError: 'TelescopeDescription' object has no attribute 'type'
```

but i notice it's in the slots:
```py3
>>> source.subarray.tel[1].__slots__
('name', 'type', 'optics', 'camera')
```

so clearly the type is not getting filled in the contructor.

2022-07-25 10:00 UTC, maxnoe commented
@kosack, fixed and test added.

2022-07-25 10:05 UTC, maxnoe commented
@kosack shall I rename `camera.camera_name` to `camera.name`? It would be more consistent with the others and not as tautological.

2022-07-25 15:19 UTC, maxnoe commented
@kosack done

2022-07-26 10:06 UTC, nbiederbeck approved these changes

2022-07-27 11:09 UTC, kosack approved these changes

2022-07-27 11:10 UTC, merged