Return tuples from SubArray properties, add suport for single value in `get_tel_ids`
cta-observatory/ctapipe pull request #2027
Opened 2022-07-18 17:54 UTC by maxnoe

The properties of `SubarrayDescription` are immutable, so the proper type is a tuple, not a list.

This also enables `get_tel_ids(<single value>)`.

2022-07-19 08:01 UTC, kosack submitted a review, later dismissed

2022-07-19 08:55 UTC, LukasNickel submitted a review, later dismissed

2022-07-19 09:40 UTC, maxnoe commented
@kosack @LukasNickel had to resolve conflicts

2022-07-19 10:27 UTC, LukasNickel submitted a review, later dismissed

2022-07-19 10:49 UTC, nbiederbeck requested changes

2022-07-19 10:49 UTC, nbiederbeck commented on ctapipe/instrument/tests/test_subarray.py
> +    tel_ids = subarray.get_tel_ids(1) == (1,)
shouldn't these be `assert`ed?

2022-07-19 11:09 UTC, maxnoe commented on ctapipe/instrument/tests/test_subarray.py
> +    tel_ids = subarray.get_tel_ids(1) == (1,)
yes

2022-07-20 10:05 UTC, LukasNickel approved these changes

2022-07-20 10:05 UTC, merged