Improve likelihood
cta-observatory/ctapipe pull request #2161
Opened 2022-12-09 16:17 UTC by StFroese

Use already implemented likelihood for muon intensity fit and catch `np.log(0)` case in likelihood

2022-12-09 16:20 UTC, StFroese commented
It's not really intuitive that this can be smaller than zero
https://github.com/cta-observatory/ctapipe/blob/ed5fdcc75744c8eb8e5a516b25b540ae1a367abf/ctapipe/image/pixel_likelihood.py#L94

2022-12-12 06:55 UTC, nbiederbeck commented
Is it feasible to not evaluate the `0` case? Width e.g. some `np.where`?

Where does `1e-323` come from? I would suppose you could use some
```python
minimal_positive_float = np.nextafter(np.float64(0), np.float64(0))
```
which is even a little smaller: `5e-324` :wink:

2022-12-12 07:25 UTC, StFroese commented
Maybe yes. The idea was to use the same safe log as in iminuit 

https://github.com/scikit-hep/iminuit/blob/e6365013ef1362b06b5acc8cd28106b61cf4bfca/src/iminuit/cost.py#L73-L75

2022-12-12 08:58 UTC, kosack requested changes

2022-12-12 08:58 UTC, kosack commented on ctapipe/image/pixel_likelihood.py
> +    neg_log_l = np.log(theta + 1e-323) + (image - prediction) ** 2 / theta
I would suggest defining `EPSILON = 1.0e-323` at the top of the file and avoid a bare number here (and also below).

2022-12-12 08:58 UTC, kosack commented on ctapipe/image/pixel_likelihood.py
> +    return -np.sum(np.log(likelihood + 1e-323))
here too

2022-12-12 08:58 UTC, kosack commented on ctapipe/image/pixel_likelihood.py
> +    mean_log_likelihood = 1 + np.log(2 * np.pi) + np.log(theta + 1e-323)
and here

2022-12-12 10:13 UTC, nbiederbeck approved these changes

2022-12-13 15:53 UTC, kosack approved these changes

2022-12-13 17:28 UTC, merged