Consistent overwrite
cta-observatory/ctapipe pull request #2213
Opened 2023-01-12 15:17 UTC by LukasNickel

- Remove all -f aliases
- Check for conflict on setup
- rename infile/outfile to input_path/output_path
- Use ToolConfigurationError everywhere

I guess that would be an API change since we remove a flag from some tools?

2023-01-12 15:23 UTC, nbiederbeck commented on ctapipe/tools/dump_triggers.py
> +            raise ToolConfigurationError("No 'input_path' parameter was specified. ")
this can be set via `allow_none=False` in L25

2023-01-13 11:14 UTC, maxnoe reviewed
Now this could be a function ...

2023-01-13 11:15 UTC, nbiederbeck approved these changes

2023-01-20 14:37 UTC, maxnoe commented on ctapipe/tools/dump_triggers.py
> +        if self.output_path.exists():
Use the new method also here?

2023-01-20 14:39 UTC, maxnoe commented on ctapipe/core/tool.py
> +    def check_output(self, output_paths):
`*output_path`

2023-01-20 15:12 UTC, maxnoe commented on ctapipe/tools/dump_triggers.py
> +            "input_path": "DumpTriggersTool.input_path",
Please change to `--input` and `--output` to be consistent with the other tools.

2023-01-20 15:43 UTC, maxnoe submitted a review, later dismissed

2023-01-23 11:58 UTC, nbiederbeck requested changes

2023-01-23 11:58 UTC, nbiederbeck commented on docs/changes/2213.api.rst
> +Remove `-f` flag as alias for `--overwrite` and fail early if output exists, but overwrite is not set
These to be double backticks, sorry.  Docs are failing bc of this.

2023-01-23 13:19 UTC, nbiederbeck approved these changes

2023-01-24 09:12 UTC, nbiederbeck commented
With the newest changes I think we would benefit from a test, checking that overwriting works explicitly.

2023-01-24 09:57 UTC, kosack submitted a review, later dismissed

2023-01-24 09:58 UTC, kosack commented on ctapipe/core/tool.py
> +                    self.log.warning(f"Overwriting {output}")
if you want Codacy to stop complaining, use 
```python
self.log.warning("Overwriting %s", output)
```
Not really critical though!

2023-01-24 11:00 UTC, maxnoe approved these changes

2023-01-24 11:23 UTC, nbiederbeck approved these changes

2023-01-24 11:33 UTC, merged

2023-02-03 09:51 UTC, maxnoe commented on ctapipe/tools/train_energy_regressor.py
> -        self.rng = np.random.default_rng(self.random_seed)
This line should have stayed, review missed it and no tests for `n_events`