Check pointing coordinate frame in DispReconstructor
cta-observatory/ctapipe pull request #2431
Opened 2023-10-26 15:12 UTC by LukasBeiske

Fixes #2427.

2023-10-26 15:52 UTC, Tobychev approved these changes

2023-10-27 08:16 UTC, maxnoe requested changes

2023-10-27 08:16 UTC, maxnoe commented on ctapipe/reco/sklearn.py
> +        if np.all(table["subarray_pointing_frame"] is CoordinateFrameType.ALTAZ):
this won't work. `is` cannot be applied element wise and these checks will always be False.

You need to check `np.all(table["subarray_pointing_frame"] == CoordinateFrameType.ALTAZ.value)`

2023-10-27 08:16 UTC, maxnoe commented on ctapipe/reco/sklearn.py
> +            ).transform_to(AltAz())
This also won't work. Transformation from ICRS to the AltAz system needs location and observation time

2023-10-27 08:16 UTC, maxnoe commented on ctapipe/reco/sklearn.py
> +            ).transform_to(AltAz())
Same as above, needs obstime and location

2023-10-27 12:25 UTC, maxnoe commented
I think this is partially already addressed (for the application  case) in #2409 and you should just throw an error if the training data is not fixed altaz

2023-10-30 11:03 UTC, Tobychev approved these changes

2023-10-30 15:13 UTC, merged