Rename single changelog file
cta-observatory/ctapipe pull request #2435
Opened 2023-10-27 19:58 UTC by StFroese

Changelog file has wrong name. Should be `bugfix.rst` and not `bug.rst`

2023-10-28 20:42 UTC, Tobychev submitted a review, later dismissed

2023-10-30 09:07 UTC, maxnoe requested changes
This bugfix was already released (PR merged August 31, 0.20 released September 11).

So renaming it so it would be included in the next release's changelog is wrong.

Please remove the file and add the entry to the `CHANGES.md` file for the 0.20 release

2023-11-17 11:35 UTC, maxnoe approved these changes

2023-11-17 12:11 UTC, Tobychev approved these changes

2023-11-17 12:23 UTC, merged