Properly transform between camera and telescope frame in muon fitter
cta-observatory/ctapipe pull request #2464
Opened 2023-11-17 15:34 UTC by maxnoe

The muon code did some strange things to transform pixel coordinates from camera to telescope frame, probably from code before camera geometries could be transformed as a whole.

2023-11-21 11:31 UTC, RuneDominik requested changes
Given that this fixes #2467 and with that the effective vs. equivalent focal-length discrepancy with, according to the issue, up to 25% differences in the muon efficiencies, I'd argue that this needs a changelog entry.

2023-11-21 11:31 UTC, RuneDominik commented on ctapipe/image/muon/tests/test_intensity_fit.py
> +    radius = 1.1959596 * u.deg
Overwritten before being used in l42 (with a slightly different value, 1.2 vs 1.1959596)

2023-11-21 11:32 UTC, maxnoe commented
@RuneDominik Yes, good point! I oversaw this change before.

2023-11-23 08:53 UTC, RuneDominik approved these changes

2023-11-29 15:33 UTC, maxnoe commented on ctapipe/image/muon/intensity_fitter.py
> +    geometry_tel_frame,
The test is through the `__call__` method of the class, there is no direct test of this method.

2023-11-29 15:36 UTC, Tobychev approved these changes

2023-12-01 08:39 UTC, kosack approved these changes

2023-12-01 08:39 UTC, merged